# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: my_proto_msg.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "zeromq.TestMessage" do
    optional :tag, :string, 1
    optional :time, :string, 2
    optional :body, :string, 3
  end
end

module Zeromq
  TestMessage = Google::Protobuf::DescriptorPool.generated_pool.lookup("zeromq.TestMessage").msgclass
end
